checks:
    php:
        code_rating: true
        duplication: true
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'
filter: {  }
coding_style:
    php:
        indentation:
            switch:
                indent_case: false
build: true

